# Generated by Django 5.0.7 on 2024-07-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backendtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('更新日', models.DateField(auto_now=True, verbose_name='更新日')),
                ('名称', models.CharField(max_length=255, verbose_name='名称')),
                ('業界_小分類', models.CharField(max_length=100, verbose_name='業界(小分類)')),
                ('求人有無', models.BooleanField(default=False, verbose_name='求人有無')),
                ('事業内容', models.TextField(verbose_name='事業内容')),
                ('所在地', models.CharField(max_length=255, verbose_name='所在地')),
                ('設立', models.DateField(verbose_name='設立')),
                ('従業員数', models.IntegerField(verbose_name='従業員数')),
                ('資本金', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='資本金')),
                ('企業URL', models.URLField(verbose_name='企業URL')),
                ('上場市場名', models.CharField(blank=True, max_length=100, verbose_name='上場市場名')),
                ('代表者', models.CharField(max_length=100, verbose_name='代表者')),
                ('平均年齢', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='平均年齢')),
            ],
        ),
    ]
