# Generated by Django 5.0.7 on 2024-07-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendtask', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='backendtask',
            new_name='CompanyList',
        ),
    ]
