# Generated by Django 5.0.7 on 2024-07-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendtask', '0005_joblist_alter_companylist_更新日_alter_companylist_求人有無'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='COMPANY_NAME',
            field=models.CharField(max_length=255, verbose_name='Company_Name'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JOB_DESCRIPTION',
            field=models.CharField(max_length=255, verbose_name='JOB_Description'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JOB_TITTLE',
            field=models.CharField(max_length=255, verbose_name='Job_Tittle'),
        ),
    ]
