# Generated by Django 5.0.6 on 2024-08-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendtask', '0006_alter_joblist_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('所在地', models.CharField(max_length=255, verbose_name='所在地')),
            ],
        ),
        migrations.CreateModel(
            name='CEONumberID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('代表電話番号', models.CharField(blank=True, max_length=20, null=True, verbose_name='代表電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('企業URL', models.URLField(blank=True, max_length=1000, null=True, verbose_name='企業URL')),
            ],
        ),
        migrations.CreateModel(
            name='URLID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('お問い合わせ先URL', models.URLField(blank=True, max_length=1000, null=True, verbose_name='お問い合わせ先URL')),
            ],
        ),
        migrations.AddField(
            model_name='companylist',
            name='お問い合わせ先URL',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='お問い合わせ先URL'),
        ),
        migrations.AddField(
            model_name='companylist',
            name='代表電話番号',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='代表電話番号'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='COMPANY_NAME',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JOB_DESCRIPTION',
            field=models.CharField(max_length=255, verbose_name='JOB Description'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JOB_TITTLE',
            field=models.CharField(max_length=255, verbose_name='JOB Tittle'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='LOCATION',
            field=models.TextField(verbose_name='Location'),
        ),
    ]
